//=============================================================
// SOEP MENU 3.0 Custom Variable Names
// Contatct :   <>
// Data     : Jul 2008
// Created  : 10 Jun 2009 at 15:51:58
//=============================================================

global DE_myvarnames
global DE_myvarnames $DE_myvarnames empstat|p195x
global DE_myvarnames $DE_myvarnames ed4job|p2265x
global DE_myvarnames $DE_myvarnames fsize|p2266x
global DE_myvarnames $DE_myvarnames nat|p2282x
global DE_myvarnames $DE_myvarnames uni|p2285x
global DE_myvarnames $DE_myvarnames mar|p2291x
global DE_myvarnames $DE_myvarnames yrsed|p2292x
global DE_myvarnames $DE_myvarnames ten|p2293x
global DE_myvarnames $DE_myvarnames hoursa|p2294x
global DE_myvarnames $DE_myvarnames hoursc|p2295x
global DE_myvarnames $DE_myvarnames hourso|p2296x
global DE_myvarnames $DE_myvarnames lfs|p2297x
global DE_myvarnames $DE_myvarnames lfsr|p2297ax
global DE_myvarnames $DE_myvarnames treiman|p638x
global DE_myvarnames $DE_myvarnames goldth|p2277x
global DE_myvarnames $DE_myvarnames oklass|p3846x
global DE_myvarnames $DE_myvarnames casmin|p4184x
global DE_myvarnames $DE_myvarnames isco1|p2279ax
global DE_myvarnames $DE_myvarnames isco2|p2279bx
global DE_myvarnames $DE_myvarnames isco4|p2279x
global DE_myvarnames $DE_myvarnames nace2|p2278x
global DE_myvarnames $DE_myvarnames nace1|p2278ax
global DE_myvarnames $DE_myvarnames nace15|p2278bx
global DE_myvarnames $DE_myvarnames naics2|p2278cx
global DE_myvarnames $DE_myvarnames kldb15|p3846ax
global DE_myvarnames $DE_myvarnames sath|p80x
global DE_myvarnames $DE_myvarnames satha|p834x
global DE_myvarnames $DE_myvarnames handicap|p489x
global DE_myvarnames $DE_myvarnames satj|p81x
global DE_myvarnames $DE_myvarnames sathh|p82x
global DE_myvarnames $DE_myvarnames sati|p83x
global DE_myvarnames $DE_myvarnames satd|p84x
global DE_myvarnames $DE_myvarnames satt|p85x
global DE_myvarnames $DE_myvarnames satcc|p86x
global DE_myvarnames $DE_myvarnames sate|p89x
global DE_myvarnames $DE_myvarnames empfirst|p1053x
global DE_myvarnames $DE_myvarnames empagain|p1055x
global DE_myvarnames $DE_myvarnames empnemp|p1057x
global DE_myvarnames $DE_myvarnames empnjob|p1063x
global DE_myvarnames $DE_myvarnames empnewbus|p1059x
global DE_myvarnames $DE_myvarnames empnochg|p1064x
global DE_myvarnames $DE_myvarnames empfirstl|p1052x
global DE_myvarnames $DE_myvarnames empagainl|p1054x
global DE_myvarnames $DE_myvarnames empnempl|p1056x
global DE_myvarnames $DE_myvarnames empnjobl|p1062x
global DE_myvarnames $DE_myvarnames empnewbusl|p1058x
global DE_myvarnames $DE_myvarnames jobpclose|p353x
global DE_myvarnames $DE_myvarnames jobretire|p355x
global DE_myvarnames $DE_myvarnames jobretirer|p355ax
global DE_myvarnames $DE_myvarnames jobtcont|p356x
global DE_myvarnames $DE_myvarnames jobendedu|p357x
global DE_myvarnames $DE_myvarnames jobfired|p358x
global DE_myvarnames $DE_myvarnames jobquitown|p359x
global DE_myvarnames $DE_myvarnames jobtranso|p360x
global DE_myvarnames $DE_myvarnames jobtransf|p361x
global DE_myvarnames $DE_myvarnames jobnowork|p362x
global DE_myvarnames $DE_myvarnames jobonleave|p363x
global DE_myvarnames $DE_myvarnames jobothreas|p364x
global DE_myvarnames $DE_myvarnames lccantdecide|p900x
global DE_myvarnames $DE_myvarnames lcmakeplans|p901x
global DE_myvarnames $DE_myvarnames lcidirect|p902x
global DE_myvarnames $DE_myvarnames lcnoavoiddes|p903x
global DE_myvarnames $DE_myvarnames lcluckget|p904x
global DE_myvarnames $DE_myvarnames lcplanreal|p905x
global DE_myvarnames $DE_myvarnames lcplanuseless|p906x
global DE_myvarnames $DE_myvarnames lchappendif|p907x
global DE_myvarnames $DE_myvarnames germcontact|p544x
global DE_myvarnames $DE_myvarnames germbelong|p557x
global DE_myvarnames $DE_myvarnames lsat10ago|p624x
global DE_myvarnames $DE_myvarnames hhnumpers|h211x
global DE_myvarnames $DE_myvarnames cjreqed|p220x
global DE_myvarnames $DE_myvarnames cjtjob|p212x
global DE_myvarnames $DE_myvarnames cjpay|p213x
global DE_myvarnames $DE_myvarnames cjadvance|p214x
global DE_myvarnames $DE_myvarnames cjhardw|p215x
global DE_myvarnames $DE_myvarnames cjdist|p216x
global DE_myvarnames $DE_myvarnames cjhourf|p217x
global DE_myvarnames $DE_myvarnames cjsocial|p218x
global DE_myvarnames $DE_myvarnames cjjobsec|p219x
global DE_myvarnames $DE_myvarnames jseek|p221x
global DE_myvarnames $DE_myvarnames jseekla|p222x
global DE_myvarnames $DE_myvarnames jseekpa|p223x
global DE_myvarnames $DE_myvarnames jseeknw|p224x
global DE_myvarnames $DE_myvarnames gwage|p295x
global DE_myvarnames $DE_myvarnames nwage|p296x
global DE_myvarnames $DE_myvarnames famwrk|p297x
global DE_myvarnames $DE_myvarnames secjob|p298x
global DE_myvarnames $DE_myvarnames occasjob|p299x
global DE_myvarnames $DE_myvarnames secjobn|p300x
global DE_myvarnames $DE_myvarnames hstat|p488x
global DE_myvarnames $DE_myvarnames hcap|p490x
global DE_myvarnames $DE_myvarnames hcapdeg|p491x
global DE_myvarnames $DE_myvarnames ndocvis|p492x
global DE_myvarnames $DE_myvarnames ndocvisn|p493x
global DE_myvarnames $DE_myvarnames hosp|p495x
global DE_myvarnames $DE_myvarnames hospt|p496x
global DE_myvarnames $DE_myvarnames hospn|p497x
global DE_myvarnames $DE_myvarnames empstatl|p498x
global DE_myvarnames $DE_myvarnames wdisab|p499x
global DE_myvarnames $DE_myvarnames wdisabf|p500x
global DE_myvarnames $DE_myvarnames wunable|p501x
global DE_myvarnames $DE_myvarnames wunabled|p502x
global DE_myvarnames $DE_myvarnames polpref|p530x
global DE_myvarnames $DE_myvarnames polident|p531x
global DE_myvarnames $DE_myvarnames polaffil|p532x
global DE_myvarnames $DE_myvarnames eventwem|p577x
global DE_myvarnames $DE_myvarnames eventmim|p580x
global DE_myvarnames $DE_myvarnames eventbim|p595x
global DE_myvarnames $DE_myvarnames eventcmm|p592x
global DE_myvarnames $DE_myvarnames eventsem|p586x
global DE_myvarnames $DE_myvarnames eventdim|p583x
global DE_myvarnames $DE_myvarnames eventsdm|p589x
global DE_myvarnames $DE_myvarnames sat|p622x
global DE_myvarnames $DE_myvarnames satf|p623x
global DE_myvarnames $DE_myvarnames isco4o|p634x
global DE_myvarnames $DE_myvarnames nace2o|p655x
global DE_myvarnames $DE_myvarnames nacep|p655x
global DE_myvarnames $DE_myvarnames gwager|p295ax
global DE_myvarnames $DE_myvarnames satreal|p6220x
global DE_myvarnames $DE_myvarnames satpred|p6230x
global DE_myvarnames $DE_myvarnames isco1o|p63401x
global DE_myvarnames $DE_myvarnames isco2o|p63402x
global DE_myvarnames $DE_myvarnames nwager|p296ax
global DE_myvarnames $DE_myvarnames empfirstd|p1053ax
global DE_myvarnames $DE_myvarnames empagaind|p1055ax
global DE_myvarnames $DE_myvarnames empnempd|p1057ax
global DE_myvarnames $DE_myvarnames empnjobd|p1063ax
global DE_myvarnames $DE_myvarnames hhnpers|h2110x
global DE_myvarnames $DE_myvarnames hhintly|h2706x
global DE_myvarnames $DE_myvarnames hhintlyr|h27060x
global DE_myvarnames $DE_myvarnames hhsacct|h2707x
global DE_myvarnames $DE_myvarnames hhlifely|h2708x
global DE_myvarnames $DE_myvarnames hhninc|h2743x
global DE_myvarnames $DE_myvarnames hhsave|h2747x
global DE_myvarnames $DE_myvarnames hhsavea|h2748x
global DE_myvarnames $DE_myvarnames hhinval|h2750x
global DE_myvarnames $DE_myvarnames hhmovedyr|h2802x
global DE_myvarnames $DE_myvarnames hhrenov|h2804x
global DE_myvarnames $DE_myvarnames hhmeters|h2805x
global DE_myvarnames $DE_myvarnames hhroomlg|h2806x
global DE_myvarnames $DE_myvarnames hhsizeh|h2807x
global DE_myvarnames $DE_myvarnames hhown|h2817x
global DE_myvarnames $DE_myvarnames hhtyp1|h2827x
global DE_myvarnames $DE_myvarnames hhtyp2|h2828x
global DE_myvarnames $DE_myvarnames state|h3111x
global DE_myvarnames $DE_myvarnames worhealth|p520x
global DE_myvarnames $DE_myvarnames visitatg|p545x
global DE_myvarnames $DE_myvarnames visitfmg|p546x
global DE_myvarnames $DE_myvarnames speakger|p547x
global DE_myvarnames $DE_myvarnames writeger|p548x
global DE_myvarnames $DE_myvarnames speakown|p549x
global DE_myvarnames $DE_myvarnames writeown|p550x
global DE_myvarnames $DE_myvarnames discrim|p552x
global DE_myvarnames $DE_myvarnames catholic|p791x
global DE_myvarnames $DE_myvarnames catholicr|p7910x
global DE_myvarnames $DE_myvarnames protestant|p792x
global DE_myvarnames $DE_myvarnames protestantr|p7920x
global DE_myvarnames $DE_myvarnames othchrist|p793x
global DE_myvarnames $DE_myvarnames othchristr|p7930x
global DE_myvarnames $DE_myvarnames nonchrist|p794x
global DE_myvarnames $DE_myvarnames nonchristr|p7940x
global DE_myvarnames $DE_myvarnames nonrelig|p795x
global DE_myvarnames $DE_myvarnames nonreligr|p795ax
global DE_myvarnames $DE_myvarnames wegener|p639x
global DE_myvarnames $DE_myvarnames sptype|p2280x
global DE_myvarnames $DE_myvarnames sppid|p2281x
global DE_myvarnames $DE_myvarnames relhead|p2222x
global DE_myvarnames $DE_myvarnames jmarried|p577ax
global DE_myvarnames $DE_myvarnames jmoveinp|p580ax
global DE_myvarnames $DE_myvarnames jchborn|p5950x
global DE_myvarnames $DE_myvarnames jchmoveout|p5920x
global DE_myvarnames $DE_myvarnames jsep|p5860x
global DE_myvarnames $DE_myvarnames jdiv|p583ax
global DE_myvarnames $DE_myvarnames jspdied|p589ax
global DE_myvarnames $DE_myvarnames hhnincr|h2743ax
global DE_myvarnames $DE_myvarnames hhsaver|h2748ax
global DE_myvarnames $DE_myvarnames hhpre|p3482x
global DE_myvarnames $DE_myvarnames hhprer|p3482ax
global DE_myvarnames $DE_myvarnames hhpost|p3483x
global DE_myvarnames $DE_myvarnames hhpostr|p3483ax
global DE_myvarnames $DE_myvarnames hhilabora|p3484x
global DE_myvarnames $DE_myvarnames hhilaborar|p3484ax
global DE_myvarnames $DE_myvarnames hhiasset|p3485x
global DE_myvarnames $DE_myvarnames hhiassetr|p3485ax
global DE_myvarnames $DE_myvarnames hhirent|p3486x
global DE_myvarnames $DE_myvarnames hhirentr|p3486ax
global DE_myvarnames $DE_myvarnames hhilabor|p3491x
global DE_myvarnames $DE_myvarnames hhilaborr|p3491ax
global DE_myvarnames $DE_myvarnames hhpostsim|p3494x
global DE_myvarnames $DE_myvarnames hhpostsimr|p3494ax
global DE_myvarnames $DE_myvarnames eqnpers|p3468x
global DE_myvarnames $DE_myvarnames eqnkids|p3469x
global DE_myvarnames $DE_myvarnames eqhoursy|p3474x
global DE_myvarnames $DE_myvarnames eqempstat|p3475x
global DE_myvarnames $DE_myvarnames eqemplev|p3476x
global DE_myvarnames $DE_myvarnames eqprimact|p3477x
global DE_myvarnames $DE_myvarnames eqocc2|p3478x
global DE_myvarnames $DE_myvarnames eqind2|p3480x
global DE_myvarnames $DE_myvarnames eqnpers0014|p3520x
global DE_myvarnames $DE_myvarnames eqnpers1518|p3521x
global DE_myvarnames $DE_myvarnames hpkw01|h2428x
global DE_myvarnames $DE_myvarnames hmotorrad|h2431x
global DE_myvarnames $DE_myvarnames hpkw012|h2430x
global DE_myvarnames $DE_myvarnames hpkw04|h2349x
global DE_myvarnames $DE_myvarnames hmotorrad_gekauft|h2432x
global DE_myvarnames $DE_myvarnames hpkw_gekauft|h2429x
global DE_myvarnames $DE_myvarnames fahrzeug2art|h2357x
global DE_myvarnames $DE_myvarnames fahrzeug1art|h2351x
global DE_myvarnames $DE_myvarnames fahrzeug3art|h2363x
global DE_myvarnames $DE_myvarnames fahrzeug4art|h2369x
global DE_myvarnames $DE_myvarnames fahrzeug1neu|h2352x
global DE_myvarnames $DE_myvarnames fahrzeug2neu|h2358x
global DE_myvarnames $DE_myvarnames fahrzeug4neu|h2370x
global DE_myvarnames $DE_myvarnames fahrzeug3neu|h2364x
global DE_myvarnames $DE_myvarnames fahrzeug1km|h2354x
global DE_myvarnames $DE_myvarnames fahrzeug2km|h2360x
global DE_myvarnames $DE_myvarnames fahrzeug3km|h2366x
global DE_myvarnames $DE_myvarnames fahrzeug4km|h2372x
global DE_myvarnames $DE_myvarnames fahrzeug1liter|h2355x
global DE_myvarnames $DE_myvarnames fahrzeug2liter|h2361x
global DE_myvarnames $DE_myvarnames fahrzeug3liter|h2367x
global DE_myvarnames $DE_myvarnames fahrzeug4liter|h2373x
global DE_myvarnames $DE_myvarnames fahrzeug1kraft|h2356x
global DE_myvarnames $DE_myvarnames fahrzeug2kraft|h2362x
global DE_myvarnames $DE_myvarnames fahrzeug3kraft|h2368x
global DE_myvarnames $DE_myvarnames fahrzeug4kraft|h2374x
global DE_myvarnames $DE_myvarnames pfhs|p685x
global DE_myvarnames $DE_myvarnames ppkwverf|p686x
global DE_myvarnames $DE_myvarnames povzeitk|p687x
global DE_myvarnames $DE_myvarnames pbahncard|p688x
global DE_myvarnames $DE_myvarnames pfhsmotrad|p681x
global DE_myvarnames $DE_myvarnames pfhslkw|p682x
global DE_myvarnames $DE_myvarnames pfhspkw|p683x
global DE_myvarnames $DE_myvarnames pfhsmoped|p684x
global DE_myvarnames $DE_myvarnames pautobegeist|p757x
global DE_myvarnames $DE_myvarnames povungern|p758x
global DE_myvarnames $DE_myvarnames pfreizuhaus|p759x
global DE_myvarnames $DE_myvarnames pumweltbew|p760x
global DE_myvarnames $DE_myvarnames entfgrstadt|h2774x
global DE_myvarnames $DE_myvarnames wohngegend|h2458x
global DE_myvarnames $DE_myvarnames gutewohngeg|h3597x
global DE_myvarnames $DE_myvarnames grundschlwohngeg|h3803x
global DE_myvarnames $DE_myvarnames inf_restaur|h2776x
global DE_myvarnames $DE_myvarnames inf_bank|h2777x
global DE_myvarnames $DE_myvarnames inf_kinderg|h2779x
global DE_myvarnames $DE_myvarnames inf_doctor|h2778x
global DE_myvarnames $DE_myvarnames inf_gymnasium|h4618x
global DE_myvarnames $DE_myvarnames inf_youthcentre|h2781x
global DE_myvarnames $DE_myvarnames inf_elderlycentre|h2782x
global DE_myvarnames $DE_myvarnames inf_transit|h2785x
global DE_myvarnames $DE_myvarnames inf_shops|h2775x
global DE_myvarnames $DE_myvarnames inf_primschool|h2780x
global DE_myvarnames $DE_myvarnames crime|h4619x
global DE_myvarnames $DE_myvarnames pollu_noise|h2786x
global DE_myvarnames $DE_myvarnames pollu_air|h2787x
global DE_myvarnames $DE_myvarnames nogreen|h2788x
global DE_myvarnames $DE_myvarnames wohng_landsleute|h2463x
global DE_myvarnames $DE_myvarnames wohng_ausl|h2790x
global DE_myvarnames $DE_myvarnames inf_green|h2783x
global DE_myvarnames $DE_myvarnames inf_sport|h2784x
global DE_myvarnames $DE_myvarnames wohng_verhaelt|h2789x
global DE_myvarnames $DE_myvarnames wohn_quartier|h2801x
global DE_myvarnames $DE_myvarnames wohn_priv_anst|h2800x
global DE_myvarnames $DE_myvarnames wohn_typ|h2799x
global DE_myvarnames $DE_myvarnames heink_korr|h4613x
global DE_myvarnames $DE_myvarnames umzug|h2621x
global DE_myvarnames $DE_myvarnames baujahr|h2803x
global DE_myvarnames $DE_myvarnames distjobkm|p267x
global DE_myvarnames $DE_myvarnames monatinterv|h4480x
global DE_myvarnames $DE_myvarnames female|p2214x
global DE_myvarnames $DE_myvarnames pequivinc|h2410x
global DE_myvarnames $DE_myvarnames hinc_2007|h4613ax
global DE_myvarnames $DE_myvarnames hpers0_1|p3522x
global DE_myvarnames $DE_myvarnames hpers2_4|p3523x
global DE_myvarnames $DE_myvarnames hpers5_7|p3524x
global DE_myvarnames $DE_myvarnames hpers8_10|p3525x
global DE_myvarnames $DE_myvarnames hpers11_12|p3526x
global DE_myvarnames $DE_myvarnames hpers13_15|p3527x
global DE_myvarnames $DE_myvarnames unifhs|p942x
global DE_myvarnames $DE_myvarnames arbeitslos|p171x
global DE_myvarnames $DE_myvarnames edu3|p4185x
global DE_myvarnames $DE_myvarnames jobchanged|p2264x
global DE_myvarnames $DE_myvarnames taetig|p1244x
