clear
set memory 700m
use "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\FHG\FHG06_08_09.dta", clear

forvalues i=1/3 {
	quietly replace f13_`i'=0 if missing(f13_`i')
	quietly replace f24_`i'=0 if missing(f24_`i')
}

gen f13 = f13_1 + f13_2*7 + f13_3*30
replace f13=  reisedauer_d if f13==0 & Jahr==2009
label var f13 "Gesamtreisedauer [d]"


gen f24_neu = f24_1 + f24_2*7 + f24_3*30 if missing(f24)
replace f24_neu = 0.5 if f24==1
replace f24_neu =  vorausbuchungszeit_d if f24_neu==0 & Jahr==2009

forvalues i=1/2 {
	quietly replace f32_`i'=0 if missing(f32_`i')
}

gen f32 = f32_1*60+f32_2
replace f32 = eintreffzeit_min if f32==0
label var f32 "Abfahrtszeit für Abflug"

label var f24_neu "Vorausbuchungszeit Flugreise; 0,5 -> Buchungstag=Flugtag"

replace f14= buchungsort if missing(f14)

label define f15 1 `"nur Flug"', modify
label define f15 2 `"Flug und zusätzliche Leistungen"', modify
label value f15 f15

recode klasse (3=4) (4=3)
replace f18=klasse if missing(f18)

replace f15=1 if missing(f15) & gebuchtes==1
replace f15=2 if missing(f15) & (gebuchtes>1 & gebuchtes<100)

gen f16 = 1 if f15==1
replace f16=gebuchtes if missing(f16)
replace f16=2 if f16_1==2
replace f16=5 if f16_1==1
replace f16=6 if f16_1==1 & f16_2==3
replace f16=3 if f16_1==3
replace f16=4 if f16_1==2 & f16_2==3

label define f16 1 `"nur Flug"', modify
label define f16 2 `"Flug und Unterkunft (getrennt)"', modify
label define f16 3 `"Flug und sonstiges"', modify
label define f16 4 `"Flug, Unterkunft und sonstiges"', modify
label define f16 5 `"Pauschalreise"', modify
label define f16 6 `"Pauschalreise und sonstiges"', modify

label value f16 f16
label var f16 "Gebuchte Leistung für Reisetab"


label define flughafen 30 `"BRE"', modify
label define flughafen 40 `"DUS"', modify
label define flughafen 50 `"CGN"', modify
label define flughafen 60 `"FRA"', modify
label define flughafen 70 `"STR"', modify
label define flughafen 80 `"NUE"', modify
label define flughafen 90 `"MUC"', modify
label define flughafen 101 `"TXL"', modify
label define flughafen 120 `"SCN"', modify
label define flughafen 140 `"LEJ"', modify
label define flughafen 150 `"DRS"', modify
label define flughafen 160 `"ERF"', modify
label define flughafen 240 `"GWT"', modify
label define flughafen 590 `"FDH"', modify
label define flughafen 605 `"FKB"', modify
label define flughafen 610 `"MHG"', modify
label define flughafen 675 `"FMM"', modify
label define flughafen 1000 `"WAW"', modify
label define flughafen 1010 `"GDN"', modify
label define flughafen 1020 `"KRK"', modify
label define flughafen 1030 `"KTW"', modify
label define flughafen 1033 `"POZ"', modify
label define flughafen 1050 `"VNO"', modify
label define flughafen 1051 `"KUN"', modify
label define flughafen 1052 `"PLQ"', modify
label define flughafen 1070 `"RIX"', modify
label define flughafen 1090 `"TLL"', modify
label define flughafen 1100 `"HEL"', modify
label define flughafen 1130 `"OUL"', modify
label define flughafen 1140 `"POR"', modify
label define flughafen 1150 `"TMP"', modify
label define flughafen 1160 `"TKU"', modify
label define flughafen 1171 `"JYV"', modify
label define flughafen 1172 `"KTT"', modify
label define flughafen 1174 `"JOE"', modify
label define flughafen 1175 `"KAJ"', modify
label define flughafen 1177 `"IVL"', modify
label define flughafen 1178 `"KAO"', modify
label define flughafen 1180 `"KUO"', modify
label define flughafen 1182 `"RVN"', modify
label define flughafen 1201 `"ARN"', modify
label define flughafen 1220 `"GOT"', modify
label define flughafen 1240 `"NRK"', modify
label define flughafen 1270 `"VBY"', modify
label define flughafen 1278 `"LPI"', modify
label define flughafen 1279 `"LLA"', modify
label define flughafen 1283 `"SFT"', modify
label define flughafen 1300 `"OSL"', modify
label define flughafen 1310 `"BGO"', modify
label define flughafen 1320 `"TRD"', modify
label define flughafen 1330 `"KRS"', modify
label define flughafen 1340 `"SVG"', modify
label define flughafen 1370 `"NVK"', modify
label define flughafen 1371 `"AES"', modify
label define flughafen 1373 `"EVE"', modify
label define flughafen 1375 `"LYR"', modify
label define flughafen 1376 `"TOS"', modify
label define flughafen 1377 `"TRF"', modify
label define flughafen 1380 `"KKN"', modify
label define flughafen 1381 `"MOL"', modify
label define flughafen 1387 `"KSU"', modify
label define flughafen 1390 `"*NO"', modify
label define flughafen 1400 `"CPH"', modify
label define flughafen 1487 `"SFJ"', modify
label define flughafen 1501 `"LHR"', modify
label define flughafen 1502 `"LGW"', modify
label define flughafen 1503 `"STN"', modify
label define flughafen 1504 `"LCY"', modify
label define flughafen 1505 `"LTN"', modify
label define flughafen 1510 `"BHX"', modify
label define flughafen 1520 `"MAN"', modify
label define flughafen 1530 `"LPL"', modify
label define flughafen 1540 `"NCL"', modify
label define flughafen 1550 `"GLA"', modify
label define flughafen 1560 `"EDI"', modify
label define flughafen 1600 `"BFS"', modify
label define flughafen 1610 `"JER"', modify
label define flughafen 1640 `"IOM"', modify
label define flughafen 1650 `"SOU"', modify
label define flughafen 1680 `"BRS"', modify
label define flughafen 1700 `"ABZ"', modify
label define flughafen 1715 `"EXT"', modify
label define flughafen 1734 `"NWI"', modify
label define flughafen 1750 `"DUB"', modify
label define flughafen 1760 `"SNN"', modify
label define flughafen 1770 `"ORK"', modify
label define flughafen 1810 `"KEF"', modify
label define flughafen 1850 `"AMS"', modify
label define flughafen 1860 `"RTM"', modify
label define flughafen 1930 `"BRU"', modify
label define flughafen 1990 `"LUX"', modify
label define flughafen 2001 `"CDG"', modify
label define flughafen 2002 `"ORY"', modify
label define flughafen 2010 `"BOD"', modify
label define flughafen 2050 `"LYS"', modify
label define flughafen 2060 `"TLS"', modify
label define flughafen 2070 `"MRS"', modify
label define flughafen 2080 `"NCE"', modify
label define flughafen 2100 `"BIA"', modify
label define flughafen 2114 `"BES"', modify
label define flughafen 2116 `"BIQ"', modify
label define flughafen 2126 `"CFR"', modify
label define flughafen 2148 `"FSC"', modify
label define flughafen 2154 `"LIL"', modify
label define flughafen 2162 `"MPL"', modify
label define flughafen 2164 `"NTE"', modify
label define flughafen 2170 `"PUF"', modify
label define flughafen 2174 `"RNS"', modify
label define flughafen 2176 `"TLN"', modify
label define flughafen 2200 `"MAD"', modify
label define flughafen 2210 `"BCN"', modify
label define flughafen 2230 `"VLC"', modify
label define flughafen 2240 `"ALC"', modify
label define flughafen 2250 `"LEI"', modify
label define flughafen 2260 `"AGP"', modify
label define flughafen 2270 `"XRY"', modify
label define flughafen 2280 `"SVQ"', modify
label define flughafen 2290 `"BIO"', modify
label define flughafen 2310 `"GRX"', modify
label define flughafen 2318 `"OVD"', modify
label define flughafen 2324 `"SCQ"', modify
label define flughafen 2328 `"VGO"', modify
label define flughafen 2350 `"PMI"', modify
label define flughafen 2360 `"IBZ"', modify
label define flughafen 2370 `"MAH"', modify
label define flughafen 2400 `"LPA"', modify
label define flughafen 2411 `"TFN"', modify
label define flughafen 2412 `"TFS"', modify
label define flughafen 2420 `"FUE"', modify
label define flughafen 2430 `"ACE"', modify
label define flughafen 2435 `"SPC"', modify
label define flughafen 2450 `"LIS"', modify
label define flughafen 2460 `"OPO"', modify
label define flughafen 2480 `"FAO"', modify
label define flughafen 2490 `"FNC"', modify
label define flughafen 2502 `"PDL"', modify
label define flughafen 2530 `"MLA"', modify
label define flughafen 2550 `"ZRH"', modify
label define flughafen 2560 `"GVA"', modify
label define flughafen 2570 `"BSL"', modify
label define flughafen 2580 `"BRN"', modify
label define flughafen 2590 `"LUG"', modify
label define flughafen 2700 `"VIE"', modify
label define flughafen 2710 `"INN"', modify
label define flughafen 2720 `"LNZ"', modify
label define flughafen 2730 `"SZG"', modify
label define flughafen 2740 `"GRZ"', modify
label define flughafen 2750 `"KLU"', modify
label define flughafen 2801 `"FCO"', modify
label define flughafen 2812 `"MXP"', modify
label define flughafen 2813 `"BGY"', modify
label define flughafen 2820 `"VCE"', modify
label define flughafen 2830 `"TRS"', modify
label define flughafen 2840 `"VRN"', modify
label define flughafen 2850 `"TRN"', modify
label define flughafen 2870 `"GOA"', modify
label define flughafen 2880 `"FLR"', modify
label define flughafen 2890 `"BLQ"', modify
label define flughafen 2900 `"PSA"', modify
label define flughafen 2920 `"NAP"', modify
label define flughafen 2930 `"BRI"', modify
label define flughafen 2940 `"BDS"', modify
label define flughafen 2950 `"SUF"', modify
label define flughafen 2970 `"CAG"', modify
label define flughafen 2980 `"OLB"', modify
label define flughafen 2990 `"PMO"', modify
label define flughafen 3000 `"CTA"', modify
label define flughafen 3005 `"AOI"', modify
label define flughafen 3040 `"REG"', modify
label define flughafen 3100 `"ATH"', modify
label define flughafen 3110 `"SKG"', modify
label define flughafen 3120 `"CFU"', modify
label define flughafen 3140 `"ZTH"', modify
label define flughafen 3170 `"SMI"', modify
label define flughafen 3180 `"JTR"', modify
label define flughafen 3190 `"KGS"', modify
label define flughafen 3200 `"RHO"', modify
label define flughafen 3210 `"CHQ"', modify
label define flughafen 3220 `"HER"', modify
label define flughafen 3230 `"KVA"', modify
label define flughafen 3240 `"MJT"', modify
label define flughafen 3248 `"GPA"', modify
label define flughafen 3258 `"PVK"', modify
label define flughafen 3264 `"JNX"', modify
label define flughafen 3300 `"ANK"', modify
label define flughafen 3301 `"ESB"', modify
label define flughafen 3310 `"IST"', modify
label define flughafen 3320 `"IZM"', modify
label define flughafen 3321 `"ADB"', modify
label define flughafen 3330 `"DLM"', modify
label define flughafen 3340 `"AYT"', modify
label define flughafen 3342 `"ADA"', modify
label define flughafen 3344 `"ASR"', modify
label define flughafen 3346 `"BJV"', modify
label define flughafen 3348 `"DIY"', modify
label define flughafen 3352 `"TZX"', modify
label define flughafen 3354 `"VAN"', modify
label define flughafen 3356 `"GZT"', modify
label define flughafen 3359 `"SZF"', modify
label define flughafen 3366 `"SAW"', modify
label define flughafen 3368 `"EZS"', modify
label define flughafen 3390 `"*TR"', modify
label define flughafen 3405 `"ECN"', modify
label define flughafen 3410 `"LCA"', modify
label define flughafen 3415 `"PFO"', modify
label define flughafen 3430 `"LJU"', modify
label define flughafen 3440 `"ZAG"', modify
label define flughafen 3450 `"SPU"', modify
label define flughafen 3460 `"DBV"', modify
label define flughafen 3470 `"PUY"', modify
label define flughafen 3476 `"RJK"', modify
label define flughafen 3478 `"ZAD"', modify
label define flughafen 3490 `"BEG"', modify
label define flughafen 3504 `"PRN"', modify
label define flughafen 3512 `"SJJ"', modify
label define flughafen 3536 `"SKP"', modify
label define flughafen 3550 `"BUD"', modify
label define flughafen 3560 `"DEB"', modify
label define flughafen 3570 `"SOB"', modify
label define flughafen 3600 `"TIA"', modify
label define flughafen 3650 `"PRG"', modify
label define flughafen 3670 `"BRQ"', modify
label define flughafen 3701 `"OTP"', modify
label define flughafen 3710 `"CND"', modify
label define flughafen 3715 `"SBZ"', modify
label define flughafen 3720 `"TSR"', modify
label define flughafen 3730 `"CLJ"', modify
label define flughafen 3732 `"IAS"', modify
label define flughafen 3750 `"SOF"', modify
label define flughafen 3760 `"VAR"', modify
label define flughafen 3770 `"BOJ"', modify
label define flughafen 3801 `"SVO"', modify
label define flughafen 3802 `"VKO"', modify
label define flughafen 3803 `"DME"', modify
label define flughafen 3810 `"LED"', modify
label define flughafen 3835 `"KGD"', modify
label define flughafen 3837 `"KUF"', modify
label define flughafen 3841 `"PEE"', modify
label define flughafen 3843 `"ROV"', modify
label define flughafen 3846 `"UFA"', modify
label define flughafen 3847 `"VOG"', modify
label define flughafen 3848 `"*XR"', modify
label define flughafen 3851 `"BAX"', modify
label define flughafen 3852 `"KJA"', modify
label define flughafen 3853 `"OMS"', modify
label define flughafen 3854 `"SVX"', modify
label define flughafen 3856 `"TOF"', modify
label define flughafen 3858 `"CEK"', modify
label define flughafen 3859 `"*XU"', modify
label define flughafen 3860 `"MSQ"', modify
label define flughafen 3880 `"KIV"', modify
label define flughafen 3890 `"IEV"', modify
label define flughafen 3891 `"KBP"', modify
label define flughafen 3892 `"DNK"', modify
label define flughafen 3893 `"LWO"', modify
label define flughafen 3894 `"ODS"', modify
label define flughafen 3895 `"SIP"', modify
label define flughafen 3897 `"DOK"', modify
label define flughafen 3900 `"TBS"', modify
label define flughafen 3910 `"EVN"', modify
label define flughafen 3921 `"GYD"', modify
label define flughafen 3930 `"ALA"', modify
label define flughafen 3937 `"TSE"', modify
label define flughafen 3960 `"ASB"', modify
label define flughafen 3970 `"TAS"', modify
label define flughafen 4000 `"CAI"', modify
label define flughafen 4010 `"ALY"', modify
label define flughafen 4020 `"LXR"', modify
label define flughafen 4040 `"HRG"', modify
label define flughafen 4055 `"RMF"', modify
label define flughafen 4060 `"SSH"', modify
label define flughafen 4100 `"TIP"', modify
label define flughafen 4150 `"TUN"', modify
label define flughafen 4160 `"DJE"', modify
label define flughafen 4170 `"MIR"', modify
label define flughafen 4200 `"ALG"', modify
label define flughafen 4240 `"*DZ"', modify
label define flughafen 4251 `"CMN"', modify
label define flughafen 4260 `"RBA"', modify
label define flughafen 4280 `"AGA"', modify
label define flughafen 4320 `"RAK"', modify
label define flughafen 4360 `"BKO"', modify
label define flughafen 4380 `"SID"', modify
label define flughafen 4382 `"RAI"', modify
label define flughafen 4400 `"DKR"', modify
label define flughafen 4420 `"BJL"', modify
label define flughafen 4480 `"FNA"', modify
label define flughafen 4520 `"ABJ"', modify
label define flughafen 4540 `"OUA"', modify
label define flughafen 4600 `"ACC"', modify
label define flughafen 4660 `"LOS"', modify
label define flughafen 4670 `"PHC"', modify
label define flughafen 4700 `"DLA"', modify
label define flughafen 4730 `"BGF"', modify
label define flughafen 4750 `"SSG"', modify
label define flughafen 4950 `"JIB"', modify
label define flughafen 4980 `"ADD"', modify
label define flughafen 5040 `"NBO"', modify
label define flughafen 5050 `"MBA"', modify
label define flughafen 5100 `"BJM"', modify
label define flughafen 5120 `"DAR"', modify
label define flughafen 5170 `"LUN"', modify
label define flughafen 5230 `"HRE"', modify
label define flughafen 5232 `"VFA"', modify
label define flughafen 5255 `"GBE"', modify
label define flughafen 5270 `"WDH"', modify
label define flughafen 5300 `"MUD"', modify
label define flughafen 5335 `"MSU"', modify
label define flughafen 5390 `"SEZ"', modify
label define flughafen 5410 `"RUN"', modify
label define flughafen 5430 `"MRU"', modify
label define flughafen 5450 `"JNB"', modify
label define flughafen 5460 `"CPT"', modify
label define flughafen 5470 `"DUR"', modify
label define flughafen 5482 `"PLZ"', modify
label define flughafen 5483 `"GRJ"', modify
label define flughafen 5490 `"*ZA"', modify
label define flughafen 5601 `"YUL"', modify
label define flughafen 5610 `"YTO"', modify
label define flughafen 5611 `"YYZ"', modify
label define flughafen 5620 `"YQB"', modify
label define flughafen 5630 `"YWG"', modify
label define flughafen 5641 `"YEG"', modify
label define flughafen 5650 `"YVR"', modify
label define flughafen 5660 `"YYC"', modify
label define flughafen 5670 `"YHZ"', modify
label define flughafen 5682 `"YOW"', modify
label define flughafen 5686 `"YQR"', modify
label define flughafen 5692 `"YYG"', modify
label define flughafen 5700 `"YXY"', modify
label define flughafen 5702 `"YYJ"', modify
label define flughafen 5740 `"*CA"', modify
label define flughafen 5751 `"JFK"', modify
label define flughafen 5753 `"EWR"', modify
label define flughafen 5770 `"BOS"', modify
label define flughafen 5780 `"PHL"', modify
label define flughafen 5790 `"BWI"', modify
label define flughafen 5801 `"IAD"', modify
label define flughafen 5811 `"DTW"', modify
label define flughafen 5850 `"IND"', modify
label define flughafen 5860 `"CLE"', modify
label define flughafen 5870 `"RIC"', modify
label define flughafen 5880 `"DAY"', modify
label define flughafen 5890 `"ALB"', modify
label define flughafen 5892 `"ROC"', modify
label define flughafen 5898 `"PWM"', modify
label define flughafen 5908 `"BDL"', modify
label define flughafen 5926 `"GRR"', modify
label define flughafen 5936 `"CMH"', modify
label define flughafen 5942 `"FWA"', modify
label define flughafen 5960 `"ATL"', modify
label define flughafen 5970 `"CLT"', modify
label define flughafen 5990 `"TPA"', modify
label define flughafen 6000 `"MIA"', modify
label define flughafen 6010 `"CHS"', modify
label define flughafen 6020 `"BNA"', modify
label define flughafen 6025 `"MEM"', modify
label define flughafen 6030 `"SDF"', modify
label define flughafen 6051 `"MCO"', modify
label define flughafen 6066 `"RDU"', modify
label define flughafen 6075 `"FLL"', modify
label define flughafen 6077 `"PBI"', modify
label define flughafen 6080 `"RSW"', modify
label define flughafen 6085 `"APF"', modify
label define flughafen 6088 `"MLB"', modify
label define flughafen 6090 `"*US2"', modify
label define flughafen 6096 `"ORD"', modify
label define flughafen 6100 `"MSP"', modify
label define flughafen 6131 `"MIQ"', modify
label define flughafen 6160 `"SPI"', modify
label define flughafen 6201 `"DFW"', modify
label define flughafen 6211 `"IAH"', modify
label define flughafen 6220 `"MSY"', modify
label define flughafen 6240 `"SAT"', modify
label define flughafen 6263 `"STL"', modify
label define flughafen 6266 `"MKC"', modify
label define flughafen 6273 `"AUS"', modify
label define flughafen 6277 `"ELP"', modify
label define flughafen 6285 `"SGF"', modify
label define flughafen 6300 `"SEA"', modify
label define flughafen 6310 `"PDX"', modify
label define flughafen 6400 `"SFO"', modify
label define flughafen 6410 `"LAX"', modify
label define flughafen 6420 `"DEN"', modify
label define flughafen 6430 `"ABQ"', modify
label define flughafen 6440 `"PHX"', modify
label define flughafen 6460 `"LAS"', modify
label define flughafen 6476 `"SMF"', modify
label define flughafen 6480 `"SAN"', modify
label define flughafen 6496 `"SJC"', modify
label define flughafen 6502 `"SNA"', modify
label define flughafen 6504 `"ASE"', modify
label define flughafen 6508 `"SLC"', modify
label define flughafen 6540 `"*US6"', modify
label define flughafen 6550 `"ANC"', modify
label define flughafen 6590 `"*US7"', modify
label define flughafen 6600 `"HNL"', modify
label define flughafen 6620 `"OGG"', modify
label define flughafen 6650 `"MEX"', modify
label define flughafen 6704 `"CUN"', modify
label define flughafen 6750 `"GUA"', modify
label define flughafen 6800 `"*BZ"', modify
label define flughafen 6820 `"SAP"', modify
label define flughafen 6850 `"SAL"', modify
label define flughafen 6890 `"SJO"', modify
label define flughafen 6930 `"HAV"', modify
label define flughafen 6940 `"VRA"', modify
label define flughafen 6946 `"HOG"', modify
label define flughafen 6960 `"FDF"', modify
label define flughafen 6980 `"NAS"', modify
label define flughafen 6985 `"FPO"', modify
label define flughafen 7000 `"KIN"', modify
label define flughafen 7010 `"MBJ"', modify
label define flughafen 7050 `"SDQ"', modify
label define flughafen 7060 `"POP"', modify
label define flughafen 7065 `"PUJ"', modify
label define flughafen 7066 `"LRM"', modify
label define flughafen 7080 `"ANU"', modify
label define flughafen 7100 `"PTP"', modify
label define flughafen 7165 `"GND"', modify
label define flughafen 7190 `"POS"', modify
label define flughafen 7220 `"AUA"', modify
label define flughafen 7224 `"BON"', modify
label define flughafen 7280 `"BOG"', modify
label define flughafen 7310 `"CLO"', modify
label define flughafen 7340 `"CCS"', modify
label define flughafen 7360 `"PMV"', modify
label define flughafen 7451 `"GIG"', modify
label define flughafen 7461 `"GRU"', modify
label define flughafen 7470 `"REC"', modify
label define flughafen 7510 `"POA"', modify
label define flughafen 7530 `"SSA"', modify
label define flughafen 7536 `"CNF"', modify
label define flughafen 7545 `"FOR"', modify
label define flughafen 7590 `"*BR"', modify
label define flughafen 7600 `"UIO"', modify
label define flughafen 7650 `"LIM"', modify
label define flughafen 7700 `"LPB"', modify
label define flughafen 7760 `"ASU"', modify
label define flughafen 7780 `"MVD"', modify
label define flughafen 7801 `"EZE"', modify
label define flughafen 7870 `"USH"', modify
label define flughafen 7900 `"SCL"', modify
label define flughafen 7930 `"PUQ"', modify
label define flughafen 7950 `"*CL"', modify
label define flughafen 7960 `"PSY"', modify
label define flughafen 8000 `"BEY"', modify
label define flughafen 8020 `"TLV"', modify
label define flughafen 8030 `"HFA"', modify
label define flughafen 8080 `"AMM"', modify
label define flughafen 8110 `"DAM"', modify
label define flughafen 8120 `"ALP"', modify
label define flughafen 8180 `"EBL"', modify
label define flughafen 8200 `"THR"', modify
label define flughafen 8201 `"IKA"', modify
label define flughafen 8213 `"SYZ"', modify
label define flughafen 8214 `"TBZ"', modify
label define flughafen 8216 `"KER"', modify
label define flughafen 8218 `"MHD"', modify
label define flughafen 8219 `"OMH"', modify
label define flughafen 8240 `"*IR"', modify
label define flughafen 8250 `"KWI"', modify
label define flughafen 8260 `"BAH"', modify
label define flughafen 8270 `"DOH"', modify
label define flughafen 8290 `"JED"', modify
label define flughafen 8340 `"SAH"', modify
label define flughafen 8380 `"MCT"', modify
label define flughafen 8410 `"DXB"', modify
label define flughafen 8420 `"AUH"', modify
label define flughafen 8450 `"KHI"', modify
label define flughafen 8460 `"ISB"', modify
label define flughafen 8500 `"DAC"', modify
label define flughafen 8520 `"KBL"', modify
label define flughafen 8550 `"DEL"', modify
label define flughafen 8570 `"BOM"', modify
label define flughafen 8580 `"MAA"', modify
label define flughafen 8590 `"NAG"', modify
label define flughafen 8600 `"GOI"', modify
label define flughafen 8610 `"BLR"', modify
label define flughafen 8626 `"TRV"', modify
label define flughafen 8628 `"COK"', modify
label define flughafen 8630 `"*IN"', modify
label define flughafen 8660 `"KTM"', modify
label define flughafen 8680 `"CMB"', modify
label define flughafen 8700 `"MLE"', modify
label define flughafen 8720 `"RGN"', modify
label define flughafen 8740 `"BKK"', modify
label define flughafen 8750 `"HKT"', modify
label define flughafen 8754 `"CNX"', modify
label define flughafen 8758 `"USM"', modify
label define flughafen 8760 `"UTH"', modify
label define flughafen 8762 `"KBV"', modify
label define flughafen 8770 `"*TH"', modify
label define flughafen 8780 `"VTE"', modify
label define flughafen 8800 `"PNH"', modify
label define flughafen 8805 `"REP"', modify
label define flughafen 8820 `"SGN"', modify
label define flughafen 8830 `"HAN"', modify
label define flughafen 8860 `"KUL"', modify
label define flughafen 8940 `"SIN"', modify
label define flughafen 8971 `"CGK"', modify
label define flughafen 8980 `"DPS"', modify
label define flughafen 9020 `"MNL"', modify
label define flughafen 9030 `"CEB"', modify
label define flughafen 9070 `"TPE"', modify
label define flughafen 9075 `"KHH"', modify
label define flughafen 9101 `"NRT"', modify
label define flughafen 9111 `"KIX"', modify
label define flughafen 9252 `"ICN"', modify
label define flughafen 9282 `"KWJ"', modify
label define flughafen 9345 `"HKG"', modify
label define flughafen 9350 `"PEK"', modify
label define flughafen 9360 `"NKG"', modify
label define flughafen 9380 `"CAN"', modify
label define flughafen 9391 `"PVG"', modify
label define flughafen 9392 `"CGQ"', modify
label define flughafen 9402 `"HRB"', modify
label define flughafen 9450 `"*CN"', modify
label define flughafen 9500 `"SYD"', modify
label define flughafen 9510 `"MEL"', modify
label define flughafen 9540 `"PER"', modify
label define flughafen 9550 `"DRW"', modify
label define flughafen 9560 `"BNE"', modify
label define flughafen 9565 `"CNS"', modify
label define flughafen 9650 `"AKL"', modify
label define flughafen 9660 `"CHC"', modify
label define flughafen 9670 `"WLG"', modify
label define flughafen 9680 `"*NZ"', modify
label define flughafen 9820 `"PPT"', modify
label define flughafen 1880 `"EIN"', modify
label define flughafen 2040 `"GNB"', modify
label define flughafen 1075 `"LPX"', modify
label define flughafen 1420 `"RNN"', modify
label define flughafen 100 `"BER"', modify
label define flughafen 1032 `"WRO"', modify
label define flughafen 1170 `"VAA"', modify
label define flughafen 1173 `"KOK"', modify
label define flughafen 1190 `"*FI "', modify
label define flughafen 1285 `"UME"', modify
label define flughafen 1372 `"ALF"', modify
label define flughafen 1379 `"HAU"', modify
label define flughafen 1410 `"AAL"', modify
label define flughafen 1590 `"CWL"', modify
label define flughafen 1718 `"HUY"', modify
label define flughafen 1719 `"INV"', modify
label define flughafen 1733 `"NQY"', modify
label define flughafen 1740 `"*GB"', modify
label define flughafen 2110 `"AJA"', modify
label define flughafen 2178 `"UIP"', modify
label define flughafen 2312 `"LCG"', modify
label define flughafen 2320 `"PNA"', modify
label define flughafen 2326 `"SDR"', modify
label define flughafen 2510 `"HOR"', modify
label define flughafen 2802 `"CIA"', modify
label define flughafen 3160 `"JMK"', modify
label define flughafen 3242 `"AOK"', modify
label define flughafen 3360 `"MLX"', modify
label define flughafen 3362 `"KYA"', modify
label define flughafen 3364 `"DNZ"', modify
label define flughafen 3506 `"TGD"', modify
label define flughafen 3680 `"BTS"', modify
label define flughafen 3685 `"KSC"', modify
label define flughafen 3700 `"BUH"', modify
label define flughafen 3833 `"ARH"', modify
label define flughafen 3834 `"GOJ"', modify
label define flughafen 3836 `"KRR"', modify
label define flughafen 3838 `"KZN"', modify
label define flughafen 3844 `"RTW"', modify
label define flughafen 3849 `"OVB"', modify
label define flughafen 3850 `"VVO"', modify
label define flughafen 3896 `"HRK"', modify
label define flughafen 3899 `"*UA"', modify
label define flughafen 3936 `"PWQ"', modify
label define flughafen 3940 `"FRU"', modify
label define flughafen 4210 `"ORN"', modify
label define flughafen 4250 `"CAS"', modify
label define flughafen 4381 `"VXE"', modify
label define flughafen 4620 `"LFW"', modify
label define flughafen 4890 `"LAD"', modify
label define flughafen 4920 `"KRT"', modify
label define flughafen 5080 `"KGL"', modify
label define flughafen 5140 `"ZNZ"', modify
label define flughafen 5180 `"LVI"', modify
label define flughafen 5350 `"TNR"', modify
label define flughafen 5360 `"*MG"', modify
label define flughafen 5642 `"YXD"', modify
label define flughafen 5688 `"YXE"', modify
label define flughafen 5698 `"YLW"', modify
label define flughafen 5716 `"YKA"', modify
label define flughafen 5802 `"DCA"', modify
label define flughafen 5810 `"DTT"', modify
label define flughafen 5820 `"PIT"', modify
label define flughafen 5840 `"BUF"', modify
label define flughafen 5894 `"SYR"', modify
label define flughafen 5896 `"BGR"', modify
label define flughafen 5916 `"SCE"', modify
label define flughafen 5918 `"ORF"', modify
label define flughafen 5930 `"MBS"', modify
label define flughafen 5946 `"CHO"', modify
label define flughafen 5947 `"CRW"', modify
label define flughafen 6040 `"SJU"', modify
label define flughafen 6050 `"ORL"', modify
label define flughafen 6063 `"TYS"', modify
label define flughafen 6067 `"CAE"', modify
label define flughafen 6068 `"GSP"', modify
label define flughafen 6071 `"BHM"', modify
label define flughafen 6073 `"MOB"', modify
label define flughafen 6078 `"PNS"', modify
label define flughafen 6082 `"TLH"', modify
label define flughafen 6086 `"EYW"', modify
label define flughafen 6095 `"CHI"', modify
label define flughafen 6165 `"CID"', modify
label define flughafen 6180 `"MSN"', modify
label define flughafen 6190 `"*US3"', modify
label define flughafen 6200 `"DAL"', modify
label define flughafen 6210 `"HOU"', modify
label define flughafen 6250 `"TUL"', modify
label define flughafen 6288 `"MFE"', modify
label define flughafen 6290 `"*US4"', modify
label define flughafen 6390 `"*US5"', modify
label define flughafen 6494 `"SBA"', modify
label define flughafen 6500 `"TUS"', modify
label define flughafen 6506 `"COS"', modify
label define flughafen 6610 `"KOA"', modify
label define flughafen 6702 `"BJX"', modify
label define flughafen 6714 `"SJD"', modify
label define flughafen 6720 `"VER"', modify
label define flughafen 6910 `"PTY"', modify
label define flughafen 7150 `"BGI"', modify
label define flughafen 7210 `"CUR"', modify
label define flughafen 7350 `"MAR"', modify
label define flughafen 7430 `"CAY"', modify
label define flughafen 7450 `"RIO"', modify
label define flughafen 7460 `"SAO"', modify
label define flughafen 7490 `"MAO"', modify
label define flughafen 7540 `"CWB"', modify
label define flughafen 7610 `"GYE"', modify
label define flughafen 7711 `"VVI"', modify
label define flughafen 7890 `"*AR"', modify
label define flughafen 8190 `"*IQ"', modify
label define flughafen 8212 `"IFN"', modify
label define flughafen 8300 `"RUH"', modify
label define flughafen 8470 `"LHE"', modify
label define flughafen 8560 `"CCU"', modify
label define flughafen 8710 `"*MV"', modify
label define flughafen 8880 `"BKI"', modify
label define flughafen 8950 `"BWN"', modify
label define flughafen 8970 `"JKT"', modify
label define flughafen 9050 `"*PH"', modify
label define flughafen 9110 `"OSA"', modify
label define flughafen 9240 `"*JP"', modify
label define flughafen 9250 `"SEL"', modify
label define flughafen 9290 `"*KR"', modify
label define flughafen 9390 `"SHA"', modify
label define flughafen 9426 `"DLC"', modify
label define flughafen 9520 `"ADL"', modify
label define flughafen 9570 `"HBA"', modify
label define flughafen 1176 `"LPP"', modify
label define flughafen 1200 `"STO"', modify
label define flughafen 1230 `"KRN"', modify
label define flughafen 1281 `"OSD"', modify
label define flughafen 1500 `"LON"', modify
label define flughafen 1620 `"GCI"', modify
label define flughafen 1690 `"EMA"', modify
label define flughafen 2158 `"LRT"', modify
label define flughafen 2182 `"NCY"', modify
label define flughafen 2314 `"MJV"', modify
label define flughafen 2332 `"ZAZ"', modify
label define flughafen 2410 `"TCI"', modify
label define flughafen 2506 `"PXO"', modify
label define flughafen 2620 `"SMV"', modify
label define flughafen 2800 `"ROM"', modify
label define flughafen 2810 `"MIL"', modify
label define flughafen 2910 `"RMI"', modify
label define flughafen 3010 `"EBA"', modify
label define flughafen 3358 `"SSX"', modify
label define flughafen 3508 `"TIV"', modify
label define flughafen 3590 `"*HU"', modify
label define flughafen 3800 `"MOW"', modify
label define flughafen 3840 `"MRV"', modify
label define flughafen 3855 `"TJM"', modify
label define flughafen 3920 `"BAK"', modify
label define flughafen 3939 `"*KZ"', modify
label define flughafen 4030 `"ASW"', modify
label define flughafen 4065 `"TCP"', modify
label define flughafen 4220 `"CZL"', modify
label define flughafen 4390 `"*CV"', modify
label define flughafen 4640 `"COO"', modify
label define flughafen 4685 `"ABV"', modify
label define flughafen 4970 `"ASM"', modify
label define flughafen 5150 `"PMA"', modify
label define flughafen 5484 `"ELS"', modify
label define flughafen 5600 `"YMQ"', modify
label define flughafen 5640 `"YEA"', modify
label define flughafen 5694 `"YYT"', modify
label define flughafen 5724 `"YXS"', modify
label define flughafen 5750 `"NYC"', modify
label define flughafen 5800 `"WAS"', modify
label define flughafen 5830 `"CVG"', modify
label define flughafen 5902 `"PVD"', modify
label define flughafen 5920 `"ROA"', modify
label define flughafen 5922 `"PHF"', modify
label define flughafen 5941 `"EVV"', modify
label define flughafen 5950 `"*US1"', modify
label define flughafen 6062 `"MKL"', modify
label define flughafen 6065 `"GSO"', modify
label define flughafen 6070 `"SAV"', modify
label define flughafen 6081 `"SRQ"', modify
label define flughafen 6083 `"VPS"', modify
label define flughafen 6140 `"DSM"', modify
label define flughafen 6150 `"MKE"', modify
label define flughafen 6155 `"PIA"', modify
label define flughafen 6181 `"FSD"', modify
label define flughafen 6284 `"LIT"', modify
label define flughafen 6286 `"OKC"', modify
label define flughafen 6490 `"MRY"', modify
label define flughafen 6498 `"RNO"', modify
label define flughafen 6944 `"CYO"', modify
label define flughafen 7180 `"TAB"', modify
label define flughafen 7325 `"CTG"', modify
label define flughafen 7410 `"PBM"', modify
label define flughafen 7520 `"BSB"', modify
label define flughafen 7710 `"SRZ"', modify
label define flughafen 7770 `"*PY"', modify
label define flughafen 7800 `"BUE"', modify
label define flughafen 8618 `"JAI"', modify
label define flughafen 8624 `"PNQ"', modify
label define flughafen 8629 `"VNS"', modify
label define flughafen 8990 `"MDC"', modify
label define flughafen 8992 `"MES"', modify
label define flughafen 9040 `"DVO"', modify
label define flughafen 9100 `"TYO"', modify
label define flughafen 9120 `"SPK"', modify
label define flughafen 9260 `"PUS"', modify
label define flughafen 9283 `"USN"', modify
label define flughafen 9330 `"ULN"', modify
label define flughafen 9396 `"CTU"', modify
label define flughafen 9408 `"SHE"', modify
label define flughafen 9418 `"WUH"', modify
label define flughafen 9530 `"CBR"', modify
label define flughafen 9575 `"LST"', modify
label define flughafen 9720 `"SPN"', modify
label define flughafen 9730 `"NAN"', modify
label define flughafen 1390 `"*NO "', modify
label define flughafen 1740 `"*GB "', modify
label define flughafen 3848 `"*RU"', modify
label define flughafen 5601 `"YMQ"', modify
label define flughafen 5801 `"WAS"', modify
label define flughafen 9101 `"TYO"', modify

label value f9 flughafen
label value destination flughafen

forvalues i=1/3 {
 label value f11_`i' flughafen
}

forvalues i=2/3 {
replace f19_`i' = 0 if missing(f19_`i')
}

save "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\FHG\FHG06_08_09_2.dta", replace
