clear
set memory 700m
usespss using "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\SPSS\Private_Reisen.sav"
save "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\STATA\\Private_Reisen.dta", replace

* global typen "Business" "Holiday" "Private"

foreach p in "Business" "Holiday" "Private" { 

use "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\STATA\\`p'_Reisen.dta", clear

label var HHID "Unique household ID (11 digits)"
label var HH_SEQNR "Internal household number (0...99999)"
label var HH_NUTS0 "Sampling country ID according to the European coding book"
label var HH_NUTS1 "Sampling region ID according to the European coding book"
label var HH_PERS "Total number of persons in household"
label var HH_U5 "Number of persons aged younger than 5"
label var HH_5_14 "Number of persons aged 5 to 14"
label var HH_O14 "Number of persons aged older than 14"
label var HH_BICY "Number of bicycles"
label var HH_MBIC "Number of motorcycles"
label var HH_PC "Number of privately owned cars"
label var HH_CC "Number of company cars"
label var HH_VEHO1 "Other vehicle - type code (see vehicles list)"
label var HH_VEHO2 "Second other vehicle - type code"
label var HH_VEHO3 "Third other vehicle - type code"
label var HH_MOBIL "Availability of mobile phone, Y/N"
label var HH_TEL "Availability of telephone, Y/N"
label var HH_FAX "Availability of fax, Y/N"
label var HH_INTER "Availability of internet, Y/N"
label var HH_COMO "Availability of other means of communication, Y/N"
label var HH_CITY "Home City"
label var HH_CTRID "Home country"
label var HH_GEOID "Geo-ID of home city"
label var HH_LRPMT "First day of last reporting month (DD.MM.YYYY)"
label var HH_LRPMT1 "Last day of last reporting month (DD.MM.YYYY)"
label var HH_ADDHJ "Number of additional holiday journeys (not reported in detail)"
label var HH_ADDPJ "Number of additional other private journeys (not reported in detail)"
label var HH_ADDBJ "Number of additional business journeys (not reported in detail)"
label var HH_ANYHJ "Holiday journeys: Y - journeys exist, O - out of period journey, N - no journeys, M - missing form, E - empty form"
label var HH_ANYPJ "Other private journeys: Y - journeys exist, O - out of period journey, N - no journeys, M – missing form, E - empty form"
label var HH_ANYBJ "Business journeys: Y - journeys exist, O - out of period journey, N - no journeys, M – missing form, E - empty form"
label var HH_PERSC "Number of persons per household enrolled in classes"
label var HH_TOTHJ "Number of detailed reported holiday journeys in total in household"
label var HH_TOTBJ "Number of detailed reported business journeys in total in household"
label var HH_TOTPJ "Number of detailed reported other private journeys in total in household"
label var HH_THJL "Number of long holiday journeys (>100km) in total in household"
label var HH_TBJL "Number of long business journeys (>100km) in total in household"
label var HH_TPJL "Number of long other private journeys (>100km) in total in household"
label var HH_THJOR "Sum of HH_TOTHJ + HH_ADDHJ (total holiday journeys originally reported of the household)"
label var HH_TPJOR "Sum of HH_TOTPJ + HH_ADDPJ (total other private journeys originally reported of the household)"
label var HH_TBJOR "Sum of HH_TOTBJ + HH_ADDBJ (total business journeys originally reported of the household)"
label var HH_THJOL "Sum of HH_THJL + HH_ADDHJ (total long holiday journeys of the household)"
label var HH_TPJOL "Sum of HH_TPJL + HH_ADDPJ (total long other private journeys of the household)"
label var HH_TBJOL "Sum of HH_TBJL + HH_ADDBJ (total long business journeys of the household)"
label var HH_AHJR "Number of recalculated additional holiday journeys (= HH_ADDHJ - ((TOTHJ-TOTHJL)*(HH_ADDHJ)/3)"
label var HH_APJR "Number of recalculated additional other private journeys (= HH_ADDPJ - ((TOTPJ-TOTPJL)*(HH_ADDPJ)/6)"
label var HH_ABJR "Number of recalculated additional business journeys (= HH_ADDBJ - ((TOTBJ-TOTBJL)*HH_ADDBJ/6)"
label var HH_THJRC "Sum of recalculated total holiday journeys of the household (=HH_THJL + HH_AHJR)"
label var HH_TPJRC "Sum of recalculated total other private journeys of the household (=HH_TPJL + HH_APJR)"
label var HH_TBJRC "Sum of recalculated total business journeys of the household (=HH_TBJL + HH_ABJR)"
label var HH_RCFH "Recalculation factor for holiday journeys (=HH_THJRC/HH_THJL or set to 0 if HH_THJL=0)"
label var HH_RCFP "Recalculation factor for other private journeys (=HH_TPJRC/HH_TPJL or set to 0 if HH_TPJL=0)"
label var HH_RCFB "Recalculation factor for business journeys (=HH_TBJRC/HH_TBJL or set to 0 if HH_TBJL=0)"
label var HH_NUTS "NUTS3 code of household's home location (geo-coded by coder)"
label var HH_EF "Household level expansion factor"
label var HH_G "Household level weight"

label var HS_INTTY "Survey method: 1 - Postal, 2 - Face to face, 3 - Telephone interview"
label var HS_SEND1 "First phase questionnaire send out date (or date of first attempt) (DD.MM.YYYY)"
label var HS_RET1 "First phase questionnaire return date (or date of interview) (DD.MM.YYYY)"
label var HS_NUMT1 "First phase total number of telephone reminders (or attempts) needed"
label var HS_NUMP1 "First phase total number of postal reminders needed"
label var HS_SEND2 "Second phase questionnaire send out date (DD.MM.YYYY)"
label var HS_RET2 "Second phase questionnaire return date (DD.MM.YYYY)"
label var HS_NUMT2 "Second phase total number of telephone reminders needed"
label var HS_NUMP2 "Second phase total number of postal reminders needed"
label var HS_RSNR1 "Reason for non-response in first phase (see Non-response codes list)"
label var HS_VALTY "Type of validation survey; “E“ if Exploration Survey, “N“ if Non-Response Survey"
label var HS_VALDT "Date of validation (DD.MM.YYYY)"
label var HS_RSNR2 "Reason for non-response in second phase (see Non-response codes list)"
label var HS_RENRV "Reason for non-response in Validation Surveys"
label var HS_RESP1 "Number of days between send out and return, (first and successful attempt), first phase (HS_SEND1 – HS_RET1)"
label var HS_RESP2 "Number of days between send out and return, second phase (HS_SEND2 – HS_RET2)"

label var P_ID "Unique person ID number"
label var P_NAME "Person’s name (maximum 50 characters)"
label var P_YEAR "Year of birth, “YYYY”"
label var P_GEND "Gender, M/ F"
label var P_EMP1 "Code of employment status (see Employment status code list)"
label var P_EMP2 "Second code of employment status"
label var P_EMP3 "Third code of employment status"
label var P_DIST "Distance to workplace or school/university (in kilometers)"
label var P_DLCS "Driver’s license, Y/ N"
label var P_PTDC "Public transport discount provided, Y/ N"
label var P_STIC "Season ticket owner, Y/ N"
label var P_AGE "Age of person"
label var P_AGEC "Age class of the person (<24=1 / 25-44=2 / 45-64=3 / 65+=4)"
label var P_TOTHJ "Number of detailed reported holiday journeys of person in total"
label var P_TOTBJ "Number of detailed reported business journeys of person in total"
label var P_TOTPJ "Number of detailed reported other private journeys of person in total"
label var P_THJL "Number of long holiday journeys (>100km) of person in total"
label var P_TBJL "Number of long business journeys (>100km) of person in total"
label var P_TPJL "Number of long other private journeys (>100km) of person in total"
label var P_DISH "Total distance of all holiday journeys traveled by person (in kilometers)"
label var P_DURH "Total duration of all holiday journeys performed by person (in days)"
label var P_DISP "Total distance of all other private journeys performed by person (in kilometers)"
label var P_DURP "Total duration of all other private journeys performed by person (in days)"
label var P_DISB "Total distance of all business journeys performed by person (in kilometres)"
label var P_DURB "Total duration of all business journeys performed by person (in days)"
label var P_EF "Person's level expansion factor"
label var P_G "Person's level weight"

label var J_ID "Unique Journey ID"
label var J_TYPE "Journey Type: H - holiday ,B - business ,P - other private journey"
label var J_LAST "Last Journey: Y - journey in reporting period, N - old journey"
* label var J_HHID "Link to HOUSEHOLD table"
label var J_NROP "Number of non-household members participating in the journey"
label var J_STRT "Start date of journey (DD.MM.YYYY)"
label var J_DUR "Duration of the journey (in number of nights)"
label var J_ORCC "Country code of departure"
label var J_ORPL "Name of departure location"
label var J_ORID "Departure location ID (from geo-coding database)"
label var J_DECC "Country code of destination"
label var J_DEID "Destination location ID (from geo-coding database)"
label var J_RECC "Country code of return location"
label var J_REPN "Name of return location"
label var J_REID "Return location ID (from geo-coding database)"
label var J_MOD1 "MAIN mode of transport code (see Modes of transport code list)"
label var J_MOD2 "Second mode of transport code (see Modes of transport code list)"
label var J_MOD3 "Third mode of transport code (see Modes of transport code list)"
label var J_MOD4 "Fourth mode of transport code (see Modes of transport code list)"
label var J_MOD5 "Fifth mode of transport code (see Modes of transport code list)"
label var J_PPID "Main purpose of journey (see list of purposes)"
label var J_ODVI "Number of other destinations visited"
label var J_NAOS "Number of additional overnight destinations"
label var J_EXJN "Additional excursions: “Y” if yes; “N” if no; “M” if missing form"
label var J_EXNR "Number of additional excursions"
label var J_VLID "1 if journey was discovered as part of Exploration Survey, otherwise 0"
label var J_EXPLOR "S if selected; N if not relevant; E if not explored"
label var J_DTCP "Indication whether the starting date is complete (day/month/year) or not (only month/year),Y YES N NO"
label var J_AGE "Age of the journey related to the date of response (Date of return of the questionnaire minus end of the journey) [in days]"
label var J_AGE_R "Same as J_AGE, if J_AGE < 1 then J_AGE_R = 1"
label var J_DIST_O "Distance between origin and destination (in kilometres)"
label var J_DIST_R "Distance between destination and return (in kilometres)"
label var J_DIST "Longest distance: J_DIST_O or J_DIST_R (in kilometres)"
label var J_SNUTS "NUTS3 code of journey's departure location"
label var J_DNUTS "NUTS3 code of journey's destination location"
label var J_RNUTS "NUTS3 code of journey's return location"

save "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\STATA\\`p'_Reisen_lab.dta", replace
}

append  using "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\STATA\Holiday_Reisen_lab.dta"
append using "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\STATA\Business_Reisen_lab.dta"
drop if missing(J_ID)
sort HHID P_ID

save "C:\Spitzencluster Luftverkehr\Modell\Nachfragedaten\DATELINE\Daten\STATA\Reisen_lab.dta", replace
